name: json_placeholder_api
description: A Dart Repository which manages the json placeholder data.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.0

  placeholder_data:
    path: ../placeholder_data

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.0.3
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^3.0.2
